from tkinter import *
def sel():
    seleccion = "Eligió Opción " + str(var.get())
    label.config(text = seleccion)
ventana = Tk()
ventana.geometry("200x100")
var = IntVar()
boton1 = Radiobutton(ventana, text="Opción 1", variable=var, value=1, command=sel)
boton1.pack( anchor = W )
boton2 = Radiobutton(ventana, text="Opción 2", variable=var, value=2, command=sel)
boton2.pack( anchor = W )
boton3 = Radiobutton(ventana, text="Opción 3", variable=var, value=3, command=sel)
boton3.pack( anchor = W)
label = Label(ventana)
label.pack()
ventana.mainloop()